### ISSUE TITLE
Problems with installation process of worxlandroid .jar file

### ISSUE THREAD

**Issue by OpenhabMat** [nibi79/worxlandroid#16]
Hello together,
I'm very interested in this package to integrate the worxlandroid-mower in the OH-World. It seems to be a very nice solution. I use openhab for several home-automation-functions-but I'm an absolute beginner...
So-I have a problem with the installation-process of this package. After copying the actual ".jar"-file in the addons-folder of my Openhab-Installation it doesn't appear in the PaperUI (configurations=things...plus). Also the manual installation-procedure didn't work.
Any idea how this could be?
- I use Openhab on a RaspberryPI3 B+.  
- My Openhab-Version is 2.4.0

Thanks in advance

**Comment by nibi79** [comment]
Hi,
sorry but OH 2.4 is not supported! 
regards
