### ISSUE TITLE
Cannot find channel type: worxlandroid:chId

### ISSUE THREAD

**Issue by KaaNee** [nibi79/worxlandroid#37]
If you open the Thing in PaperUI an error will be logged:

2020-06-04 21:52:44.083 [WARN ] [ore.internal.thing.ThingTypeResource] - Cannot find channel type: worxlandroid:chId

As watched in the code, it should be fixed already, but needs a new version to have this fixed on user-side, too ;-)

Regards,
Kai

**Comment by nibi79** [comment]
As we 've found, you use an old version!
