### ISSUE TITLE
Error-Logentry: failed installing, but works

### ISSUE THREAD

**Issue by KaaNee** [nibi79/worxlandroid#39]
After using the correct and newest version now ([1.0](https://github.com/nibi79/worxlandroid/releases/tag/v1.0)), i get 
[ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-worxlandroid'
sometimes, repeating.

I read the update instructions, removed the old mower, stopped openhab, replaced the jar, started openhab and found the mower in the inbox, working all fine right now.

**Comment by nibi79** [comment]
That's not a problem of the binding itself.
