### ISSUE TITLE
Error connecting to Worx Landroid WebApi! 

### ISSUE THREAD

**Issue by achim42** [nibi79/worxlandroid#41]
I'm a newbie. 
On a openhabian system (newest version) I tried to set up the bridge to worx (version 1.0) and got an error message.
Tried to DEBUG the bundle org.openhab.bindings.worxlandroid - doesn't help much.
All I get is this:

2020-06-05 14:11:16.893 [DEBUG] [nternal.webapi.request.WebApiRequest] - URI: https://api.worxlandroid.com/api/v2/oauth/token
==> /var/log/openhab2/events.log <==
2020-06-05 14:11:16.893 [me.event.ThingUpdatedEvent] - Thing 'worxlandroid:worxlandroidBridge:cbe5bf61' has been updated.
==> /var/log/openhab2/openhab.log <==
2020-06-05 14:11:17.667 [ERROR] [ternal.webapi.WorxLandroidWebApiImpl] - Error connecting to Worx Landroid WebApi! Error = org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header

Additional information: Login on worx-europe.com with username achim.hermann was possible.

Any help appreciated ;)

**Comment by nibi79** [comment]
Please check your credentials. You have to use the same credentials as you use for the original landroid app!

**Comment by achim42** [comment]
Moin.

OK, I have
Vorname / prename         achim
Nachname / surname      hermann
Anzeigename                     achim.hermann

and password                    xxxxxxxxxx

Works with
https://worx-europe.com/mein-konto/
very well.

I use Anzeigename and the password  to complete the definitions for the bridge (inside openhab).

But - doesn't work.

Greetings
Achim


sent by mobile

------------------------------------------------------------------
Impetus Unternehmensberatung GmbH
Mergenthalerallee 77
65760 Eschborn
Telefon:     +49 (0) 69 713 74 99 - 40
Mobile:      +49 (0) 173 377 47 98
Fax:            +49 (0) 69 713 74 99 - 99
Email:        Achim.Hermann@impetus.biz
Homepage:  www.impetus.biz<http:// www.impetus.biz>
------------------------------------------------------------------
Geschäftsführer: Achim Hermann
Sitz der Gesellschaft: Frankfurt am Main
HRB-Nr.: 74487
Handelsgericht: Frankfurt am Main

UstG-Nr.: DE136780040

________________________________

**Comment by nibi79** [comment]
Hi Achim,

I'm sure your credentials are not correct! I get the same error when I use wrong credentials.

The URL for the API is **https://api.worxlandroid.com** and not **https://worx-europe.com/mein-konto/**. These are definitely different accounts! 

I think when you set up your mower with the landroid app then you create the account for the API. And I'm also sure the username must be an e-mail address.

So again... you have to use the same credentials as you use for the original landroid app! You can test it with the landroid app. Open the app, go to "Konto", click "Logout" and try to log in with you Worx-europe.com credentials. That will not work! There is also a button for reset your password.

**Comment by MikeTheTux** [comment]
Here you can test the API login: [https://account.worxlandroid.com/login](https://account.worxlandroid.com/login)

**Comment by achim42** [comment]
Sorry for not answering. My father was in hospital and died last wednesday.
Will be back in ten days and proceed with the configuration and the test.
I will inform about the results.
Please allow answering for 12 more days.

Greetings
Achim


sent by mobile

------------------------------------------------------------------
Impetus Unternehmensberatung GmbH
Mergenthalerallee 77
65760 Eschborn
Telefon:     +49 (0) 69 713 74 99 - 40
Mobile:      +49 (0) 173 377 47 98
Fax:            +49 (0) 69 713 74 99 - 99
Email:        Achim.Hermann@impetus.biz
Homepage:  www.impetus.biz<http:// www.impetus.biz>
------------------------------------------------------------------
Geschäftsführer: Achim Hermann
Sitz der Gesellschaft: Frankfurt am Main
HRB-Nr.: 74487
Handelsgericht: Frankfurt am Main

UstG-Nr.: DE136780040
________________________________

**Comment by MatzeMuc86** [comment]
Having same issues but can login successfully to https://id.eu.worx.com/
Even openhab get data some times. Any known issue / limitation?
I use: refreshStatusInterval=60, pollingInterval=300
