### ISSUE TITLE
.items on github wrong

### ISSUE THREAD

**Issue by JimboJones3101** [nibi79/worxlandroid#46]
Hey there,

just a minor thing I just discovered. In your .items you describe the sundays-schedule as 

`// Sunday
Number          LandroidScheduleSundayStartHour         "Start Hour [%d]"                   <time>                  {channel="worxlandroid:mower:MyWorxBridge:MySerialNumber:datScSunday#scheduleStartHour"}
Number          LandroidScheduleSundayStartMinutes      "Start Minutes [%d]"                <time>                  {channel="worxlandroid:mower:MyWorxBridge:MySerialNumber:datScSunday#scheduleStartMinutes"}
Number          LandroidScheduleSundayDuration          "Duration [%d]"                     <time>                  {channel="worxlandroid:mower:MyWorxBridge:MySerialNumber:datScSunday#scheduleDuration"}
Switch          LandroidScheduleSundayEdgecut           "Edgecut "                          <settings>              {channel="worxlandroid:mower:MyWorxBridge:MySerialNumber:datScSunday#scheduleEdgecut"}`

but it should be

`// Sunday
Number          LandroidScheduleSundayStartHour         "Start Hour [%d]"                   <time>                  {channel="worxlandroid:mower:MyWorxBridge:MySerialNumber:cfgScSunday#scheduleStartHour"}
Number          LandroidScheduleSundayStartMinutes      "Start Minutes [%d]"                <time>                  {channel="worxlandroid:mower:MyWorxBridge:MySerialNumber:cfgScSunday#scheduleStartMinutes"}
Number          LandroidScheduleSundayDuration          "Duration [%d]"                     <time>                  {channel="worxlandroid:mower:MyWorxBridge:MySerialNumber:cfgScSunday#scheduleDuration"}
Switch          LandroidScheduleSundayEdgecut           "Edgecut "                          <settings>              {channel="worxlandroid:mower:MyWorxBridge:MySerialNumber:cfgScSunday#scheduleEdgecut"}`

You described it as `datScSunday` but it should be `cfgScSunday` (according to the working other weekdays) so it correctly polls the data. Within the current setup Sundays aren't polled neither can this day be adjusted.

**Comment by nibi79** [comment]
You're right!

I've already fixed this with commit [e69bf2a](https://github.com/nibi79/worxlandroid/commit/e69bf2ad26d59bbf4d7546b4e2d8a16ea5177aa1#diff-04c6e90faac2675aa89e2176d2eec7d8) and only merged this branch to master today.

Thank you for contributing!
