### ISSUE TITLE
Worx API block

### ISSUE THREAD

**Issue by mitch-geht-ab** [nibi79/worxlandroid#52]
Hi @nibi79 ,

I have some problems with the worx api.
It stoped working during I played a bit arrount with it:
```
21:37:03.934 [DEBUG] [internal.webapi.request.WebApiRequest] - Worx Landroid WebApi Response: {"id":348326,"email":"xxxxxxxx","name":"Thomas","surname":"gehtab","user_type":"customer","locale":"en","push_notifications":true,"location":{"latitude":xxxxxxx,"longitude":xxxxxxx},"terms_of_use_agreed":true,"marketing_consent":null,"profiling_consent":null,"advertising_consent":null,"country_id":276,"mqtt_endpoint":"a1optpg91s0ydf-ats.iot.eu-west-1.amazonaws.com","actions_on_google_pin_code":null,"created_at":"2020-07-12 10:28:34","updated_at":"2020-07-12 11:48:22"}
21:37:03.940 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'worxlandroid:worxlandroidBridge:26e59d1c' has been updated.
21:37:03.941 [INFO ] [id.internal.WorxLandroidBridgeHandler] - Start retrieving AWS certificate
21:37:03.943 [DEBUG] [internal.webapi.request.WebApiRequest] - URI: https://api.worxlandroid.com/api/v2/users/certificate
21:37:04.073 [DEBUG] [internal.webapi.request.WebApiRequest] - Worx Landroid WebApi Response: {"id":214395,"pkcs12":"***hidden for debug log***","active":false,"created_at":"2020-07-12 10:59:29","updated_at":"2020-07-12 10:59:29"}
21:37:04.076 [ERROR] [id.internal.WorxLandroidBridgeHandler] - Connection blocked from Worx, please try again in 24h
```

On landroid-bridge my account is working like a charm.
```
landroid_1  | [2020-07-18T19:22:22.240] [DEBUG] IoBrokerAdapter - users/me: {"id":348326,"email":"xxxxxxxx","name":"Thomas","surname":"gehtab","user_type":"customer","locale":"en","push_notifications":true,"location":{"latitude":xxxxxxxx,"longitude":xxxxxxxxx},"terms_of_use_agreed":true,"marketing_consent":null,"profiling_consent":null,"advertising_consent":null,"country_id":276,"mqtt_endpoint":"a1optpg91s0ydf-ats.iot.eu-west-1.amazonaws.com","actions_on_google_pin_code":null,"created_at":"2020-07-12 10:28:34","updated_at":"2020-07-12 11:48:22"}
landroid_1  | [2020-07-18T19:22:22.241] [DEBUG] IoBrokerAdapter - Mqtt url: a1optpg91s0ydf-ats.iot.eu-west-1.amazonaws.com
landroid_1  | [2020-07-18T19:22:22.246] [DEBUG] IoBrokerAdapter - xxxxxxx<my JWT base64 stuff>xxxxxxxxxxx
landroid_1  | [2020-07-18T19:22:22.506] [DEBUG] IoBrokerAdapter - AWS certificate done
```

Is it possible to request a new client certificate for the oh2 binding?
And why is there another id in the WebApi Response? Shouldn't be mine?

I've allready uninstalled the binding from OH2, restarted OH2 and waited.
Waited ~28h for the first retry and >48h for the last.
Have also cleared the OH2 cache.
The pkcs12 id is always the same and maybe the inactive pkcs12?

Would be great to hear from you.

BR
Mitch

**Comment by nibi79** [comment]
Hi Mitch,

I cannot explain what Worx is doing and when they block the certificate or your IP address. 
But it's not possible to request a new certificate. It's always and for all applications the same certificate.

Please take a look to this post:
https://community.openhab.org/t/worx-landroid-binding/95246/171?u=nibi79

**Comment by mitch-geht-ab** [comment]
Hi nibi79

> Please take a look to this post:
> https://community.openhab.org/t/worx-landroid-binding/95246/171?u=nibi79

Yes I saw this.
Will try it today or tomorrow.

Could you imagine to implement the TRACE log level and output thinks like mqtt communication, public part of the pkcs12 and maybe connectionids?

**Comment by mitch-geht-ab** [comment]
> > Please take a look to this post:
> > https://community.openhab.org/t/worx-landroid-binding/95246/171?u=nibi79
> 
> Yes I saw this.
> Will try it today or tomorrow.

Okay, unpairing my landroid and reconnect worked.
Just for completion this is the sollution from the openhab community forum:

> solved it with unpairing the mower in the worx account and than readd the mover via app and qrcode again. Of course
> also delete everything in OH (things, items etc.) After that the connection to aaws servers worked immediately. But, be sure
> you wait the 24h again 

> Could you imagine to implement the TRACE log level and output thinks like mqtt communication, public part of the pkcs12 and maybe connectionids?

After upgrading from OH 2.5.5 to 2.5.7 your binding is working like a charm. Maybe there was a bug in 2.5.5 in conjunction with your binding.
And I can also see MQTT topics on DEBUG log level.

Despite all this i would like to say thank you for all the work you have done so far and the enthusiasm to develop and support this binding.

BR
Mitch
