### ISSUE TITLE
Dependency in oh3

### ISSUE THREAD

**Issue by maschenborn** [nibi79/worxlandroid#57]
In OpenHab 3 there's missing a dependency:
If this is a small issue, I would be happy if you could help...

`2020-10-28 07:34:18.109 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/openhab/addons/org.openhab.binding.worxlandroid-2.5.3-SNAPSHOT.jar

org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.worxlandroid [307]

  Unresolved requirement: Import-Package: org.eclipse.smarthome.config.discovery`

**Comment by LukasA83** [comment]
I created an OH3 compatible version, see open pull request.
