### ISSUE TITLE
Connection blocked from Worx

### ISSUE THREAD

**Issue by CP64** [nibi79/worxlandroid#69]
Hi,

first thank you for providing this great Binding.
But I have a issue to connetct the Bridge. I get always following Message : COMMUNICATION_ERROR
Connection blocked from Worx, please try again in 24h!

Any Idea how to solve it.
I use OH3 

![Worx Error](https://user-images.githubusercontent.com/89038437/162151154-dcb788d7-0d42-42b5-811a-935a293eb330.JPG)

Thank You

**Comment by foobar26** [comment]
Just alter the two config values for the bridge and reduce the number of calls to the Worx API. I set them to `refreshStatusInterval=3600, pollingInterval=3600`
After that I was never blocked again.

**Comment by keldi23** [comment]
Hi, 

since a few days my account is also blocked.
I have stopped the openhab docker for 5 days now. 
Today I started it again but it is almost blocked.
Can someone help me?

Thank you

**Comment by foobar26** [comment]
> Hi,
> 
> since a few days my account is also blocked. I have stopped the openhab docker for 5 days now. Today I started it again but it is almost blocked. Can someone help me?
> 
> Thank you

Did you try to unlink the worx from your account and reconnect it afterwards.
This helped in my case.
