### ISSUE TITLE
Make 'polling' and 'refreshStatus' interval for mowers configurable

### ISSUE THREAD

**Issue by nibi79** [nibi79/worxlandroid#8]
There are 2 background jobs for the mower:

- refreshStatusJob (interval=1minute)
- pollingJob (interval=5minutes)

The intervals should be configurable.

**Comment by int5749** [comment]
Hi,
this should be changed carefully, because account is locked down is intervall is to fast

**Comment by DonStefano** [comment]
For me, the mention error did not reappear in log after setting refresh status interval to 300 and polling interval to 500.
