### ISSUE TITLE
AWS MQTT Exception: The connection was closed unexpectedly

### ISSUE THREAD

**Issue by BobMiles** [nibi79/worxlandroid#82]
Hi,

first of all, thank you so much for this amazing binding. I got it up and running with OH3.4 and it worked quite well for some days . until today the thing stopped working and when I tried to reconnect the bridge (disable/enable) it now always hangs on INITIALIZING. THe log shows the following exception:

`2023-05-19 12:06:50.122 [ERROR] [worxlandroid.internal.mqtt.AWSClient] - Exception: software.amazon.awssdk.crt.mqtt.MqttException: The connection was closed unexpectedly.`

I have not changed anything in the configuration. Any idea how to solve this?

Thank you so much and all the best,

Bob

**Comment by BetaHydri** [comment]
Same here, after ~24h of running, it seems that the my account is somehow locked out to send MQTT to the worx AWS MQTT endpoint. Even the Android App has now connection errors, can't change any settings via the App as well. My quick solution was to transfer my Landroid to an other email account. But I ran into the same issue after approximately 24h.

[](Beitrag im Thema "Landroid S Unpair / Pair" https://www.roboter-forum.com/threads/landroid-s-unpair-pair.62726/post-851524)

**Comment by BetaHydri** [comment]
> Now that you mention it, my ios app throws connection errors, too. I can't change or command anything. Maybe it really is locked up because of excessive usage through the binding? I'll wait a day or two and see what happens...

Yes, I disabled the Binding (Bridge) on my rasberry (Openhab 3.4.4)  for now and I will also wait 24h-48h and hope that at least the Worx App will be ok...

**Comment by BetaHydri** [comment]
After approx. 24h my account was unblocked, WorxLandroidBridgeHandler was able to connect again to AWS. I have now set the Landroid thing representing my S300 to:

- Refresh status interval (300 sec)
- Polling interval (300 sec)
- Reconnect interval to AWS (1200 sec)

In the Openhab logs I can see that reconnection to AWS happens now every 30min. The docs mentioned that 599 sec is the max? 
It seems to be 7200 sec for the AWS reconnection interval.

**Comment by BetaHydri** [comment]
After approx. 24h my account was unblocked, WorxLandroidBridgeHandler was able to connect again to AWS. I have now set the Landroid thing representing my S300 to:

- Refresh status interval (300 sec)
- Polling interval (300 sec)
- Reconnect interval to AWS (1200 sec)

In the Openhab logs I can see that reconnection to AWS happens now every 30min. The docs mentioned that 599 sec is the max? It seems to be 7200for the AWS reconnection interval.

**Comment by BobMiles** [comment]
> After approx. 24h my account was unblocked, WorxLandroidBridgeHandler was able to connect again to AWS. I have now set the Landroid thing representing my S300 to:
> 
> * Refresh status interval (300 sec)
> * Polling interval (300 sec)
> * Reconnect interval to AWS (1200 sec)
> 
> In the Openhab logs I can see that reconnection to AWS happens now every 30min. The docs mentioned that 599 sec is the max? It seems to be 7200 sec as max. for the AWS reconnection interval.

Thanks for the update, I did the account transfer to get it working again, but sadly I can tell you that I got blocked again with the following settings:
Refresh: 600
Polling: 900
Reconnect 599

**Comment by BetaHydri** [comment]
Same here today at ~10PM I was blocked also again.

**Comment by sihui62** [comment]
> Refresh: 600
> Polling: 900
> Reconnect 599

Please use these settings (Refreswh 1200, Polling 3600, Reconnect 0 or 300), runs since 5 weeks without any problems here:

https://github.com/nibi79/worxlandroid/issues/73#issuecomment-1507984587

**Comment by BobMiles** [comment]
> > Refresh: 600
> > Polling: 900
> > Reconnect 599
> 
> Please use these settings (Refreswh 1200, Polling 3600, Reconnect 0 or 300), runs since 5 weeks without any problems here:
> 
> [#73 (comment)](https://github.com/nibi79/worxlandroid/issues/73#issuecomment-1507984587)

Thank you so much! I dug through the original issue this morning and also saw that the setting are what makes or breaks this binding. Maybe it should state that in the instructions for new users. I might add that once I have it up and running again.

**Comment by BetaHydri** [comment]
> > > Refresh: 600
> > > Polling: 900
> > > Reconnect 599
> > 
> > 
> > Please use these settings (Refreswh 1200, Polling 3600, Reconnect 0 or 300), runs since 5 weeks without any problems here:
> > [#73 (comment)](https://github.com/nibi79/worxlandroid/issues/73#issuecomment-1507984587)
> 
> Thank you so much! I dug through the original issue this morning and also saw that the setting are what makes or breaks this binding. Maybe it should state that in the instructions for new users. I might add that once I have it up and running again.

Hi, I got the information from another German forum, that the worx account is limited to **150 MQTT request per day**. So this limit will be reached quite fast with approx 150 x 9.6 requests/minutes = 1440 min (24h).

**Comment by BetaHydri** [comment]
> > > Refresh: 600
> > > Polling: 900
> > > Reconnect 599
> > 
> > 
> > Please use these settings (Refreswh 1200, Polling 3600, Reconnect 0 or 300), runs since 5 weeks without any problems here:
> > [#73 (comment)](https://github.com/nibi79/worxlandroid/issues/73#issuecomment-1507984587)
> 
> Thank you so much! I dug through the original issue this morning and also saw that the setting are what makes or breaks this binding. Maybe it should state that in the instructions for new users. I might add that once I have it up and running again.

Hi, I got the information from another German forum, that the worx account is limited to **150 MQTT request per day**. So this limit will be reached quite fast with approx 150 x 9.6 requests/minutes.

**Comment by nibi79** [comment]
Does it work for everyone now? Can we close this issue?

**Comment by BobMiles** [comment]
> Does it work for everyone now? Can we close this issue?

Yes, it's working for me. Thanks for merging the Docs!

**Comment by BetaHydri** [comment]
> > information from another German forum
> 
> Can you give me the link, please?
> 
> > 150 MQTT request per day
> 
> per day or last 24h?
> 
> > 150  x 9.6 requests/minute = 1440 min (24h)
> 
> I don't understand your calculation!?

Sorry nibi79 didn't realized that you aks about the link: I found it here in the discussion of a german fhem forum: https://forum.fhem.de/index.php?topic=111959.msg1175725#msg1175725

Regarding the calculation, I only pointed out how many requests/day it would theoretically possible until the 24h lockout of the worx account would happen. 
So, if there are no other requests e.g. from the android worx app, then maybe ~9 request/min may be possible? 
1440min / 9.6request/min = 150 requests

**Comment by RolandRosenfeld** [comment]
>       So, if there are no other requests e.g. from the android worx app, then maybe ~9 request/min may be possible?
>       1440min / 9.6request/min = 150 requests
I think that is mathematically wrong.  If you have 1440 min and 9.6 req/min than the result is 1440 min*9.6 req/min = 13824 req.

So if 150 requests are allowed we have 150 req/1440 min = 0.104 req/min.
So you are allowed to send one request per 10 minutes.
