### ISSUE TITLE
[Landroid V4] MQTT connection closes after some hours

### ISSUE THREAD

**Issue by clinique** [nibi79/worxlandroid#90]
After installation, the binding worked very well. Now I had to restart OpenHAB once. Since then I get the following error message:

`[ERROR] [worxlandroid.internal.mqtt.AWSClient] - Exception: software.amazon.awssdk.crt.mqtt.MqttException: The connection was closed unexpectedly.`

**Comment by sihui62** [comment]
After an openHAB restart the binding does not work, regardless of setting in Reconnect interval, disabling and reenabling the Bridge Thing solves the problem.

**Comment by sihui62** [comment]
> After an openHAB restart the binding does not work

After clearing tmp and cache folders and several restarts of openHAB4 because of adaption of other bindings from OH3 to OH4 this issue is gone for me.
