### ISSUE TITLE
[Landroid V4] Channels do not populate any data

### ISSUE THREAD

**Issue by sihui62** [nibi79/worxlandroid#92]
OH version: openHAB 4.0.0 Build #3544
Binding version: 4.0.0.202307021742
Worx Mower M500 Plus WR165E

~~`<weekday>#time` channels do not populate any data (NULL), for example~~

~~`DateTime Worx_ScheduleSundayTime "Start time" {channel="worxlandroid:mower:mower:m500plus:sunday#time"}`~~
~~In the old version we had two separate channels, hour and minute:~~
~~`cfgScSaturday#scheduleStartHour` and~~
~~`cfgScSaturday#scheduleStartMinutes`~~

The above statement is only true for weekdays where the schedule is set to inactive. Means it is no error at all  :-)

Same for `battery#charge-cycle`: (NULL)

`Number WorxLandroidMowerBatteryChargeCycle "Battery charge cycle total" {channel="worxlandroid:mower:mower:m500plus:battery#charge-cycle"}`

**Comment by clinique** [comment]
@sihui62 : charge-cycle should now be solved in the new version I'm pushing on the 09/26/23. There was a typo in resource naming.

**Comment by sihui62** [comment]
> should now be solved

I will try to test tomorrow, thx a lot.

**Comment by sihui62** [comment]
Fixed with Binding version 4.1.0.202309261327, thx a ton.
