### ISSUE TITLE
[Landroid V4] No label text on Bridge Thing for configuration of IP adress

### ISSUE THREAD

**Issue by sihui62** [nibi79/worxlandroid#94]
The help/label text is missing for the IP adress in the configuration parameter for the Bridge thing.

https://community.openhab.org/t/worx-landroid-binding/95246/310

**Comment by ilumie802** [comment]
I do not see that issue with the newest version: https://github.com/clinique/marketplace/blob/main/org.openhab.binding.worxlandroid-4.1.0-SNAPSHOT.jar

**Comment by sihui62** [comment]
Correct, is already fixed
