### ISSUE TITLE
v3.4.1 incompatible with OH4

### ISSUE THREAD

**Issue by zskadar** [nibi79/worxlandroid#96]
Hi nibi71,

the latest version of the binding worked fine with OH 3.4, I've unfortunately upgraded my system to OH 4.0.1, what is the latest stable. If the binding is in addons folder, the OH4 restarts continuously. The only messge in the log: 
[WARN ] [ernal.webapi.response.WebApiResponse] - Cannot get response as JsonObject.

I've moved the jar file to an another folder, OH4 started properly. I've tried to move back to the addons folder, the system worked until this message again. 
I've tried set debug for the binding, everything seemed good, there was not any issue with the binding itself, but after a few seconds, I've got the same message, OH4 freezed, systemd restarted the daemon. OH4 is based on Java version 17, instead of version 11, what OH3.x uses. I'm not a programmer, but unfortunately this isn't work right now.

OH Version:     4.0.1 (Build)
Landroid binding: 3.4.1
Java:
openjdk version "17.0.8" 2023-07-18 LTS
OpenJDK Runtime Environment Zulu17.44+15-CA (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.44+15-CA (build 17.0.8+7-LTS, mixed mode, sharing)
OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS

**Comment by zskadar** [comment]
I've found the compatible version, it worX again, thanks :)

**Comment by FranzSchi** [comment]
@zskadar, which is the Version you found and where?

**Comment by FranzSchi** [comment]
This one?
https://github.com/clinique/marketplace/blob/main/org.openhab.binding.worxlandroid-4.1.0-SNAPSHOT.jar

**Comment by zskadar** [comment]
@FranzSchi , yes, but I'm on stable OH train, so I use v4.0.0.
